<?php

$check = $_POST['input'];

$software = array("Advance" ,
    "Approval" ,
    "Classic" ,
    "Geographic Scope" ,
    "Guarantee" ,
    "Infringement" ,
    "Licensed Product" ,
    "Licensee" ,
    "Licensing Agent" ,
    "Licensing Agent" ,
    "Licensor",
    "LIMA" ,
    "Minimum" ,
    "Property" ,
    "Royalty" ,
    "Royalty Auditing" ,
    "Style Guide" ,
    "Term",
    "Terms" ,
    "TV Ratings" ,
    "Facts and Figures",
    "Sending Occasions",
    "as defined in ",
    "applicable ",
    "perpetual",
    "exclusive",
    "non-exclusive",
    "non-transferable",
    "transferable",
    "expressly ",
    "intellectual property ",
    "hereunder",
    "infringe",
    "subsidiaries",
    "INDEMNIFICATION",
    "hereby",
    "indemnifies",
    "contravention",
    "third party",
    "indemnifies ",
    "infringes or otherwise violates",
    "indemnitor ",
    "indemnitee ",
    //generic terms
    "Action",
);

$housing = array(
    "arrears" => "over due rent",
    "assignment" => "this property is under your care now!",
    "automatic renewal clause" => "When you lease ends. it can be automatically renewed! ",
    "breach" => "breaking a rule",
    "caveat emptor",
    "civil" => "none crime case. Judge Judy style",
    "constructive eviction",
    "contract" => "an agreement",
    "damages" => "how much money ether you our your landlord has to pay due to financial loss",
    "default" => "going back on the agreement in any way (usually not paying rent)",
    "eviction" => "eviction",
    "dispossess" => "eviction",
    "exculpatory clause" => "amnesty from a negligent or wrongful act",
    "exculpatory" => "the end of the lease by its own method (lease time runs out)",
    "fixed term tenancy" => "the lease ends upon a end of lease date",
    "fixtures" => "things attached to the property like sinks and light sockets",
    "holdover tenancy" => "when you maintain possession of the premises after the term of lease has expired",
    "housing code" => " Regulations written by a state, county, or local government which establish certain minimum standards of habitability for residential property.  ",
    "judgment" => "the decision of the court",
    "landlord" => "the owner of the property",
    "lease"  => "an agreement between you and the land lord for length of time and for a specified cost",
    "lesse" => "You",
    "lessor" => "The landlord",
    "liability" => "being responsible for",
    "mitigate"  => "taking action to make damages less costly or severe",
    "notice" => "an oral or written forewarning of a legal event",
    "notice of petition to recover possession of real property" => "states the grounds for eviction and the remedy that is being sought.  ",
    "parties" =>"people involved in the legal contract",
    "periodic tenancy" =>"month to month",
    "premises" =>"The property refered to in the lease",
    "property" =>"real estate that one has the legal right to possess, use, and enjoy",
    "quit" =>"to leave or vacate",
    "remedy" =>"correcting a wrong doing",
    "rent" =>"the agreed upon sum of money between you and your landlord to be payed at fixed intervals",
    "retaliatory eviction" =>"an attempt by a landlord to evict you for complaining about housing code violations to the appropriate enforcement agency (this does not end well for the landlord)",
    "right to quiet and peaceful enjoyment" =>"the landlord has the right to actually rent the place",
    "security deposit" =>"money desposited by you to secure the full and faithful following of the lease",
    "sublease" =>"leasing by you too another of the property you are renting",
    "summary proceeding" =>"the legal process the landlord must follow to evict you",
    "tenant" =>"You",
    "tenancy" =>"the period of time you are the tenent",
    "term" =>"a period of time in which the lease grants",
    "termination" =>"the purposful end of a rental agreement",
    "warrant" =>"A document that grants authority to do something",
    "warranty of habitability" =>"An implied warranty in every lease (even if it is not stated explicitly in the lease) that the condition of the premises rented is free of any defects that might harm the health, safety, or welfare of the tenants"
);
//parse
//

header("Location: index.php");
?>